services:
  db:
    restart: always
    image: mariadb:latest
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=qwiz
      - MARIADB_USER=qwiz
      - MARIADB_PASSWORD=qwiz
    ports:
      - "3307:3306"
  app:
    user: "${UID}:${GID}"
    build: 
      context: ./php
    restart: always
    volumes:
      - ./backend:/srv/app
    ports:
      - "9000:9000"
    depends_on:
      - db
  caddy:
    user: "${UID}:${GID}"
    build: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./backend:/srv/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
volumes:
  caddy_data:
  caddy_config: