services:
  db:
    restart: always
    image: mariadb:latest
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=qwiz
      - MARIADB_USER=qwiz
      - MARIADB_PASSWORD=qwiz
    ports:
      - "3307:3306"

  app:
    user: "1000:1000"
    build:
      context: ./php
    restart: always
    volumes:
      - ./backend:/srv/app
    ports:
      - "9000:9000"
    depends_on:
      - db

  caddy:
    user: "1000:1000"
    build: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./backend:/srv/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  node:
    restart: always
    user: "1000:1000"
    image: node:latest
    tty: true
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"
      - "3000:3000"
    depends_on:
      - caddy

volumes:
  caddy_data:
  caddy_config:
